routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {return view('front.pages.home'); })->name('home');
Route::get('/contact', function () {return view('front.pages.contact'); })->name('contact');
Route::get('/blog', function () {return view('front.pages.blog'); })->name('blog');
Route::get('/blog/{id}', function () {return view('front.pages.blog.details'); })->name('blog.details');
Route::get('/orders', function () {return view('front.pages.ordering'); })->name('front.order');
Route::get('/services', function () {return view('front.pages.services'); })->name('services');

Route::get('/login', 'MerchantController@loginView')->name('login');
Route::post('/authentication', 'MerchantController@authenticate')->name('authentication');

Route::get('/password_forget', function (){ return view('merchant.pages.passwordForget');})->name('passwordForget');

Route::get('/inscription', function (){
    if(Auth::user()){
        return view('merchant/pages/dashboard');
    }
    return view('front.pages.register');})->name('register');

Route::post('/inscription', 'MerchantController@create')->name('MerchantCreate');

Route::prefix('admin')->name('admin.')->group(function () {

    Route::permanentRedirect('', '/admin/dashboard');

    Route::get('home', function () {
        return view('admin/index');
    })->name('index');

    Route::get('dashboard', function () {
        return view('admin/pages/dashboard');
    })->name('dashboard');

    Route::get('login', function () {
        return view('admin/pages/login');
    })->name('login');

    Route::get('lock', function () {
        return view('admin/pages/lock');
    })->name('lock');

    Route::get('register', function () {
        return view('admin/pages/register');
    })->name('register');


    Route::get('recover', function () {
        return view('admin/pages/recover');
    })->name('recover');

    Route::get('error', function () {
        return view('admin/pages/error', ['code' => 400, 'message' => 'Page not found']);
    })->name('error');
});

Route::middleware(['App\Http\Middleware\Logged', 'App\Http\Middleware\Merchant'])->prefix('merchant')->name('merchant.')->group(function () {
    Route::get('/', 'MerchantController@dashboard' )->name('dashboard');

    Route::get('commandes', 'MerchantController@order')->name('orders');

    Route::get('equipe', 'MerchantController@staffList')->name('staff.list');
    Route::post('equipe', 'MerchantController@staffAdd')->name('staff.add');

    Route::get('stock', 'MerchantController@supplier')->name('suppliers');
    Route::get('stock/{id}/produits', 'MerchantController@product')->name('product');
    Route::get('horaires', 'MerchantController@timesheet')->name('timesheet');

    Route::get('parametres', 'MerchantController@setting')->name('setting');
});

Route::any('/deconnexion', function (){ Auth::logout(); return redirect('/');})->name('logout');

app/Http/Controllers/MerchantController.php
<?php

    namespace App\Http\Controllers;

    use App\Http\Requests\MerchantLoginRequest;
    use App\Http\Requests\UserRequest;
    use App\Http\Services\AuthenticationService;
    use App\Http\Services\MerchantService;
    use App\Http\Services\OrderService;
    use App\Http\Services\ProductService;
    use App\Http\Services\StockService;
    use App\Http\Services\SupplierService;
    use App\Http\Services\UserService;
    use Illuminate\Http\Request;
    use Illuminate\Support\Facades\Auth;
    use Illuminate\Foundation\Auth\RegistersUsers;

    class MerchantController extends Controller
    {
        use RegistersUsers;
        protected $userService;
        protected $orderService;
        protected $authService;
        protected $merchantService;
        protected $productService;
        protected $supplierService;
        protected $stockService;

        public function __construct(AuthenticationService $authService,UserService $userService, MerchantService $merchantService, SupplierService $supplierService, StockService $stockService, ProductService $productService , OrderService $orderService){
            $this->userService = $userService;
            $this->authService = $authService;
            $this->orderService = $orderService;
            $this->productService = $productService;
            $this->merchantService = $merchantService;
            $this->supplierService = $supplierService;
            $this->stockService = $stockService;
        }

        public function dashboard() {
            return view('merchant/pages/dashboard');
        }

        public function order() {
            $orders = $this->orderService->getAllSOrderByStore(Auth::user()->store_id);
            return view('merchant/pages/orders', compact('orders'));
        }

        public function staffList() {
            $store = $this->merchantService->getStoreByUser(Auth::user());
            $employees = $this->userService->getAllUserByStore(Auth::user()->store_id);
            return view('merchant/pages/team', compact(['employees', 'store']));
        }

        public function supplier() {
            $suppliers = $this->supplierService->getSuppliersAndPRoductsByStore();
            //$suppliers = $this->stockService->getStockProductAndSupplier();
            return view('merchant/pages/suppliers', compact('suppliers'));
        }

        public function product(int $supplier_id) {
            $supplier = $this->supplierService->getSupplier($supplier_id);
            $products = $this->productService->getProductBySupplierAndStore($supplier_id, Auth::user()->store_id);
            //dd($products, $supplier);
            return view('merchant/pages/product', compact('products', 'supplier'));
        }

        public function timesheet() {
            return view('merchant/pages/timesheet');
        }

        public function setting() {
            return view('merchant/pages/setting');
        }

        public function staffAdd(Request $request) {
            $this->userService->createUser($request->all(), Auth::user()->store_id);
            return redirect()->route('merchant.staff.list');
        }

        public function authenticate(MerchantLoginRequest $request)
        {
            $remember = key_exists('remember', $request->all());
            $session = $this->authService->login($request->only('email', 'password'), $remember);
            if ($session){
                return redirect()->route('merchant.dashboard');
            }
            return back()->withInput()->withErrors([
                'email' => "Nom d'utilisateur ou mot de passe incorrect",
            ]);
        }

        public function create (UserRequest $request)
        {
            $data = $request->all();
            $store = $this->merchantService->createStore($data);
            $this->userService->createUser($data, $store);

            $this->authenticate($request);
           return redirect()->route('merchant.dashboard');
        }

        public function loginView()
        {
            return view('/front/pages/login');
        }
    }

resources/views/merchant/pages/error.blade.php
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">

    <!-- Libs CSS -->
    <link rel="stylesheet" href="{{asset('')}}/fonts/feather/feather.min.css">
    <link rel="stylesheet" href="{{asset('')}}/libs/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="{{asset('')}}/libs/quill/dist/quill.core.css">
    <link rel="stylesheet" href="{{asset('')}}/libs/select2/dist/css/select2.min.css">
    <link rel="stylesheet" href="{{asset('')}}/libs/highlight.js/styles/vs2015.css">

    <!-- Map -->
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css' rel='stylesheet' />

    <!-- Theme CSS -->

    <link rel="stylesheet" href="{{asset('')}}/css/theme.min.css" id="stylesheetLight">

    <link rel="stylesheet" href="{{asset('')}}/css/theme-dark.min.css" id="stylesheetDark">

    <style>body { display: none; }</style>


    <title>Dashkit</title>
</head>
<body class="d-flex align-items-center bg-auth border-top border-top-2 border-primary">

<!-- CONTENT
================================================== -->
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-5 col-xl-4 my-5">

            <div class="text-center">

                <!-- Preheading -->
                <h6 class="text-uppercase text-muted mb-4">
                    404
                </h6>

                <!-- Heading -->
                <h1 class="display-4 mb-3">
                    Aucune page ici 😭
                </h1>

                <!-- Subheading -->
                <p class="text-muted mb-4">
                    On dirait que vous avez atterri ici par accident ?
                </p>

                <!-- Button -->
                <a href="{{route('marchand.dashboard')}}" class="btn btn-lg btn-primary">
                    Retournez à votre tableau de bord
                </a>

            </div>

        </div>
    </div> <!-- / .row -->
</div> <!-- / .container -->

<!-- JAVASCRIPT
================================================== -->
<!-- Libs JS -->
<script src="{{asset('')}}/libs/jquery/dist/jquery.min.js"></script>
<script src="{{asset('')}}/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="{{asset('')}}/libs/%40shopify/draggable/lib/es5/draggable.bundle.legacy.js"></script>
<script src="{{asset('')}}/libs/autosize/dist/autosize.min.js"></script>
<script src="{{asset('')}}/libs/chart.js/dist/Chart.min.js"></script>
<script src="{{asset('')}}/libs/dropzone/dist/min/dropzone.min.js"></script>
<script src="{{asset('')}}/libs/flatpickr/dist/flatpickr.min.js"></script>
<script src="{{asset('')}}/libs/highlightjs/highlight.pack.min.js"></script>
<script src="{{asset('')}}/libs/jquery-mask-plugin/dist/jquery.mask.min.js"></script>
<script src="{{asset('')}}/libs/list.js/dist/list.min.js"></script>
<script src="{{asset('')}}/libs/quill/dist/quill.min.js"></script>
<script src="{{asset('')}}/libs/select2/dist/js/select2.min.js"></script>
<script src="{{asset('')}}/libs/chart.js/Chart.extension.min.js"></script>

<!-- Map -->
<script src='https://api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.js'></script>

<!-- Theme JS -->
<script src="{{asset('')}}/js/theme.min.js"></script>

</body>

<!-- Mirrored from dashkit.goodthemes.co/error.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 18 Sep 2019 23:43:29 GMT -->
</html>

resources/views/merchant/pages/lock.blade.php
    <!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Greeva - Responsive Bootstrap 4 Admin Dashboard</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <!-- App favicon -->
        <link rel="shortcut icon" href="assets/images/favicon.ico">

        <!-- App css -->
        <link href="assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="assets/css/icons.min.css" rel="stylesheet" type="text/css" />
        <link href="assets/css/app.min.css" rel="stylesheet" type="text/css" />

    </head>

    <body class="authentication-bg authentication-bg-pattern d-flex align-items-center">

        <div class="home-btn d-none d-sm-block">
            <a href="index.html"><i class="fas fa-home h2 text-white"></i></a>
        </div>

        <div class="account-pages w-100 mt-5 mb-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-8 col-lg-6 col-xl-5">
                        <div class="card">

                            <div class="card-body p-4">

                                <div class="text-center mb-4">
                                    <a href="index.html">
                                        <span><img src="assets/images/logo-dark.png" alt="" height="28"></span>
                                    </a>
                                </div>

                                <div class="text-center">
                                    <img src="assets/images/users/avatar-1.jpg" alt="user-image" class="img-thumbnail avatar-xl rounded-circle">
                                    <p class="text-muted my-3">Enter your password to access the admin.</p>
                                </div>

                                <form action="#" class="pt-2">

                                    <div class="form-group mb-3">
                                        <label for="password">Password</label>
                                        <input class="form-control" type="password" required="" id="password" placeholder="Enter your password">
                                    </div>

                                    <div class="form-group mb-0 text-center">
                                        <button class="btn btn-success btn-block" type="submit"> Log In </button>
                                    </div>

                                </form>

                                <div class="row mt-3">
                                    <div class="col-12 text-center">
                                        <p class="text-muted mb-0">Not you? return <a href="auth-login.html" class="text-dark ml-1"><b>Sign In</b></a></p>
                                    </div> <!-- end col -->
                                </div>
                                <!-- end row -->

                            </div> <!-- end card-body -->
                        </div>
                        <!-- end card -->

                    </div> <!-- end col -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
        </div>
        <!-- end pages -->

        <!-- Vendor js -->
        <script src="assets/js/vendor.min.js"></script>

        <!-- App js -->
        <script src="assets/js/app.min.js"></script>

    </body>
</html>

resources/views/merchant/pages/passwordForget.blade.php
@extends('front.alternative')
@section('title')
    <title>Mot de passe oublié</title>
@stop
@section('content')
        <div class="col-12 col-md-5 col-xl-4 my-5">

            <!-- Heading -->
            <h1 class="display-4 text-center mb-3">
                Password reset
            </h1>

            <!-- Subheading -->
            <p class="text-muted text-center mb-5">
                Enter your email to get a password reset link.
            </p>

            <!-- Form -->
            <form>

                <!-- Email address -->
                <div class="form-group">

                    <!-- Label -->
                    <label>Email Address</label>

                    <!-- Input -->
                    <input type="email" class="form-control" placeholder="name@address.com">

                </div>

                <!-- Submit -->
                <button class="btn btn-lg btn-block btn-primary mb-3">
                    Reset Password
                </button>

                <!-- Link -->
                <div class="text-center">
                    <small class="text-muted text-center">
                        Remember your password? <a href="sign-in.html">Log in</a>.
                    </small>
                </div>

            </form>

        </div>
@endsection

resources/views/merchant/pages/product.blade.php
@extends('merchant.index')
@section('content')
    <!-- HEADER -->
    <div class="header">

        <!-- Image -->

        <div class="container-fluid">

            <!-- Body -->
            <div class="header-body mt-n3 mt-md-n4">
                <div class="row align-items-end">
                    <div class="col-auto">

                        <!-- Avatar -->
                        <div class="avatar avatar-xxl header-avatar-top">
                            <img src="{{$supplier->logo}}" alt="..." class="avatar-img rounded-circle border border-4 border-body">
                        </div>

                    </div>
                    <div class="col mb-3 ml-n3 ml-md-n2">

                        <!-- Pretitle -->
                        <h6 class="header-pretitle">
                            Fournisseur
                        </h6>

                        <!-- Title -->
                        <h1 class="header-title">
                            {{$supplier->name}}
                        </h1>

                    </div>
                    <div class="col-12 col-md-auto mt-2 mt-md-0 mb-md-3">

                        <!-- Button -->
                        <a href="mailto:{{$supplier->email}}"
                           class="btn btn-secondary d-block d-md-inline-block lift"
                           data-toggle="tooltip" data-placement="top" data-original-title="{{$supplier->email}}" >
                            <i class="fe fe-send"></i>
                        </a>
                        <a href="tel:{{$supplier->phone}}"
                           class="btn btn-secondary d-block d-md-inline-block lift"
                           data-toggle="tooltip" data-placement="top" data-original-title="{{$supplier->phone}}" >
                            <i class="fe fe-phone-call"></i>
                        </a>
                    </div>
                </div> <!-- / .row -->
                <div class="row align-items-center">
                    <div class="col">

                        <!-- Nav -->
                        <ul class="nav nav-tabs nav-overflow header-tabs">
                            <li class="nav-item">
                                <a href="{{route('merchant.suppliers')}}" class="nav-link">
                                    Stock
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link active">
                                    Produits
                                </a>
                            </li>
                        </ul>

                    </div>
                </div>
            </div> <!-- / .header-body -->

        </div>
    </div>

    <!-- CONTENT -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">

                <!-- Files -->
                <div class="card" data-toggle="lists" data-options="{&quot;valueNames&quot;: [&quot;name&quot;]}">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col">

                                <!-- Title -->
                                <h4 class="card-header-title">
                                    Files
                                </h4>

                            </div>
                            <div class="col-auto">

                                <!-- Dropdown -->
                                <div class="dropdown">

                                    <!-- Toggle -->
                                    <a href="#" class="small text-muted dropdown-toggle" data-toggle="dropdown">
                                        Sort order
                                    </a>

                                    <!-- Menu -->
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item sort" data-sort="name" href="#!">
                                            Asc
                                        </a>
                                        <a class="dropdown-item sort" data-sort="name" href="#!">
                                            Desc
                                        </a>
                                    </div>

                                </div>

                            </div>
                            <div class="col-auto">

                                <!-- Button -->
                                <a href="#!" class="btn btn-sm btn-primary">
                                    Upload
                                </a>

                            </div>
                        </div> <!-- / .row -->
                    </div>
                    <div class="card-header">
                        <div class="row">
                            <div class="col-12">

                                <!-- Form -->
                                <form>
                                    <div class="input-group input-group-flush input-group-merge">
                                        <input type="search" class="form-control form-control-prepended search" placeholder="Search">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text">
                                                <span class="fe fe-search"></span>
                                            </div>
                                        </div>
                                    </div>
                                </form>

                            </div>
                        </div> <!-- / .row -->
                    </div>
                    <div class="card-body">

                        <!-- List -->
                        <ul class="list-group list-group-lg list-group-flush list my-n4">
                            @foreach($products as $product)
                                <li class="list-group-item px-0">

                                <div class="row align-items-center">
                                    <div class="col-auto">

                                        <!-- Avatar -->
                                        <a href="#!" class="avatar avatar-lg">
                                            <img src="{{asset('')}}/img/files/file-3.jpg" alt="..." class="avatar-img rounded">
                                        </a>

                                    </div>
                                    <div class="col ml-n2">

                                        <!-- Title -->
                                        <h4 class="card-title mb-1 name">
                                            <a href="#!">{{$product->name}}</a>
                                        </h4>

                                        <!-- Text -->
                                        <p class="card-text small text-muted mb-1">
                                            750kb JPG
                                        </p>

                                        <!-- Time -->
                                        <p class="card-text small text-muted">
                                            Uploaded by Dianna Smiley on <time datetime="2018-01-03">Jan 3, 2018</time>
                                        </p>

                                    </div>
                                    <div class="col-auto">

                                        <!-- Button -->
                                        <a href="#!" class="btn btn-sm btn-white d-none d-md-inline-block">
                                            Download
                                        </a>

                                    </div>
                                    <div class="col-auto">

                                        <!-- Dropdown -->
                                        <div class="dropdown">
                                            <a href="#" class="dropdown-ellipses dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fe fe-more-vertical"></i>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a href="#!" class="dropdown-item">
                                                    Action
                                                </a>
                                                <a href="#!" class="dropdown-item">
                                                    Another action
                                                </a>
                                                <a href="#!" class="dropdown-item">
                                                    Something else here
                                                </a>
                                            </div>
                                        </div>

                                    </div>
                                </div> <!-- / .row -->

                            </li>
                            @endforeach
                        </ul>

                    </div>
                </div>

            </div>
        </div> <!-- / .row -->
    </div>
@endsection

resources/views/merchant/pages/suppliers.blade.php
@extends('merchant.index')
@section('content')
        <!-- HEADER -->
        <div class="header">

            <!-- Image -->
            <div class="container-fluid">

                <!-- Body -->
                <div class="header-body">
                    <div class="row align-items-end">
                        <div class="col">

                            <!-- Pretitle -->
                            <h6 class="header-pretitle">
                                Overview
                            </h6>

                            <!-- Title -->
                            <h1 class="header-title">
                                Fournisseurs
                            </h1>

                        </div>
                    </div> <!-- / .row -->

                    <div class="row align-items-center">
                        <div class="col">

                            <!-- Nav -->
                            <ul class="nav nav-tabs nav-overflow header-tabs">
                                <li class="nav-item">
                                    <a class="nav-link">
                                        Liste
                                    </a>
                                </li>
                            </ul>

                        </div>
                    </div>
                </div> <!-- / .header-body -->

            </div>
        </div>

        <!-- CONTENT -->
        <div class="container-fluid">
            <div class="row">
                @foreach($suppliers as $supplier)
                    <div class="col-12 col-lg-6">

                    <!-- Card -->
                    <div class="card">
                        <div class="card-body">
                            <!-- Avatar -->
                            <div class="text-center">
                                <span class="card-avatar avatar avatar-lg mx-auto">
                                    <img src="{{$supplier->logo}}" alt="" class="avatar-img rounded">
                                </span>
                            </div>

                            <!-- Title -->
                            <h2 class="card-title text-center mb-3">
                                <span>{{$supplier->name}}</span>
                            </h2>

                            <!-- Text -->

                            <p class="card-text text-center text-muted">
                                <i class="fe fe-phone text-pink "></i> : {{$supplier->phone}}
                            </p>
                            <p class="card-text text-center text-muted">
                                <i class="fe fe-send"></i> : {{$supplier->email}}
                            </p>

                            <!-- Divider -->
                            <hr>

                            <div class="row align-items-center">
                                <div class="col">

                                    <!-- Time -->
                                    <a href="{{route('merchant.product', ['id' => $supplier->id])}}" class="card-text small text-muted">
                                        <i class="fe fe-clipboard"></i> Produits
                                    </a>

                                </div>
                                <div class="col-auto">

                                    <!-- Avatar group -->
                                    <div class="avatar-group">
                                        @foreach($supplier as $storeProduct)
                                            <a href="profile-posts.html" class="avatar avatar-xs" data-toggle="tooltip" title="" data-original-title="Ab Hadley">
                                            <img src="{{$storeProduct}}" class="avatar-img rounded-circle" alt="...">
                                        </a>
                                        @endforeach
                                    </div>

                                </div>
                            </div> <!-- / .row -->

                        </div> <!-- / .card-body -->
                    </div>

                </div>
                @endforeach
            </div> <!-- / .row -->
        </div>
@endsection