routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {return view('front.pages.home'); })->name('home');
Route::get('/contact', function () {return view('front.pages.contact'); })->name('contact');
Route::get('/blog', function () {return view('front.pages.blog'); })->name('blog');
Route::get('/blog/{id}', function () {return view('front.pages.blog.details'); })->name('blog.details');
Route::get('/orders', function () {return view('front.pages.ordering'); })->name('front.order');
Route::get('/services', function () {return view('front.pages.services'); })->name('services');

Route::get('/login', 'MerchantController@loginView')->name('login');
Route::post('/authentication', 'MerchantController@authenticate')->name('authentication');

Route::get('/password_forget', function (){ return view('merchant.pages.passwordForget');})->name('passwordForget');

Route::get('/inscription', function (){
    if(Auth::user()){
        return view('merchant/pages/dashboard');
    }
    return view('front.pages.register');})->name('register');

Route::post('/inscription', 'MerchantController@create')->name('MerchantCreate');

Route::prefix('admin')->name('admin.')->group(function () {

    Route::permanentRedirect('', '/admin/dashboard');

    Route::get('home', function () {
        return view('admin/index');
    })->name('index');

    Route::get('dashboard', function () {
        return view('admin/pages/dashboard');
    })->name('dashboard');

    Route::get('login', function () {
        return view('admin/pages/login');
    })->name('login');

    Route::get('lock', function () {
        return view('admin/pages/lock');
    })->name('lock');

    Route::get('register', function () {
        return view('admin/pages/register');
    })->name('register');


    Route::get('recover', function () {
        return view('admin/pages/recover');
    })->name('recover');

    Route::get('error', function () {
        return view('admin/pages/error', ['code' => 400, 'message' => 'Page not found']);
    })->name('error');
});

Route::middleware(['App\Http\Middleware\Logged', 'App\Http\Middleware\Merchant'])->prefix('merchant')->name('merchant.')->group(function () {
    Route::get('/', 'MerchantController@dashboard' )->name('dashboard');

    Route::get('commandes', 'MerchantController@order')->name('orders');

    Route::get('equipe', 'MerchantController@staffList')->name('staff.list');
    Route::post('equipe', 'MerchantController@staffAdd')->name('staff.add');

    Route::get('stock', 'MerchantController@supplier')->name('suppliers');
    Route::get('stock/{id}/produits', 'MerchantController@product')->name('product');
    Route::get('horaires', 'MerchantController@timesheet')->name('timesheet');

    Route::get('parametres', 'MerchantController@setting')->name('setting');
});

Route::any('/deconnexion', function (){ Auth::logout(); return redirect('/');})->name('logout');

resources/views/front/partials/footer.blade.php
<!-- footer -->
<footer class="footer secondery-bg">
    <div class="footer-top pt-110 pb-70">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <!-- footer widget -->
                    <div class="footer-widget">
                        <div class="widget-title">
                            <h3>Addresse</h3>
                        </div>
                        <p>Yopougon Milionaire</p>
                        <p> 225 Abidjan, Côte d'Ivoire</p>
                    </div>
                    <!-- End of footer widget -->
                </div>

                <div class="col-md-4">
                    <!-- footer widget -->
                    <div class="footer-widget text-center">
                        <div class="widget-title">
                            <h3>Nous Suivre</h3>
                        </div>
                        <div class="footer-social-area">
                            <ul class="social-list mb--0 list-unstyled">
                                <li>
                                    <a href="#"><i class="fa fa-twitter"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-facebook"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-pinterest"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-youtube"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- End of footer widget -->
                </div>

                <div class="col-md-4">
                    <!-- footer widget -->
                    <div class="footer-widget text-right">
                        <div class="widget-title">
                            <h3>Contacts</h3>
                        </div>
                        <div class="footer-contact-info">
                            <a href="tel:+22586656587">+225 86 65 65 87</a>
                            <a href="mailto:support@gazloc.com">support@gazloc.com</a>
                        </div>
                    </div>
                    <!-- End of footer widget -->
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom text-center">
        <div class="footer-bottom-text">
            <p>© Copyright 2019 par <a href="https://www.ainotek.com">Ainotek.com</a></p>
        </div>
    </div>
</footer>
<!-- End of footer -->

resources/views/front/partials/header.blade.php
<!-- Main header -->
<header class="header">
    <!-- Start Header Navbar-->
    <div class="main-header">
        <div class="main-menu-wrap">
            <div class="container-fluide">
                <div class="row align-items-center">
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-4 col-6">
                        <!-- Logo -->
                        <div class="logo">
                            <a href="{{route('home')}}">
                                <img src="{{asset('')}}/img/logo.png" data-rjs="2" alt="mineralo">
                            </a>
                        </div>
                        <!-- End of Logo -->
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-4 col-sm-4 col-6 menu-button">
                        <div class="menu--inner-area clearfix">
                            <div class="menu-wraper">
                                <nav>
                                    <!-- Header-menu -->
                                    <div class="header-menu dosis">
                                        <ul>
                                            <li class="{{ Request::routeIs('home') ? 'active' : '' }}">
                                                <a href="{{route('home')}}">Accueil <img src="{{asset('')}}/img/line2.png" alt=""></a>
                                            </li>
                                            <li class="{{ Request::routeIs('front.order') ? 'active' : '' }}">
                                                <a href="{{route('front.order')}}">Commander <img src="{{asset('')}}/img/line2.png" alt=""></a>
                                            </li>
                                            <li class="{{ Request::routeIs('services') ? 'active' : '' }}">
                                                <a href="{{route('services')}}">Services<img src="{{asset('')}}/img/line2.png" alt=""></a>
                                            </li>

                                            <li class="{{ Request::routeIs('contact') ? 'active' : '' }}">
                                                <a href="{{route('contact')}}">Contact<img src="{{asset('')}}/img/line2.png" alt=""></a>
                                            </li>
                                            <li class="{{ Request::routeIs('blog') ? 'active' : '' }}">
                                                <a href="{{route('blog')}}">Blog/Infos <img src="{{asset('')}}/img/line2.png" alt=""></a>
                                            </li>
                                        </ul>
                                    </div>
                                    <!-- End of Header-menu -->
                                </nav>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-4">
                        <div class="urgent-call text-right">
                            <div class="top-right ">
                                @auth
                                    <a href="{{ route('merchant.dashboard') }}" class="mr-2">Mon Compte</a>
                                    <a href="{{ route('logout') }}" class="ml-2">Deconnexion</a>
                                @else
                                    <a href="{{ route('login') }}" class="mr-2">Connexion</a>
                                    <a href="{{ route('register') }}" class="ml-2">Enregistrement</a>
                                @endauth
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Header Navbar-->
</header>
<!-- End of Main header -->

resources/views/front/partials/parteners.blade.php
<!-- our partner -->
<section class="pt-120 pb-120 boxed-shadow">
    <div class="container">
        <div class="row">
            <div class="col">
                <!-- partner carosel inner -->
                <div class="partner-carousel-wrap">
                    <div class="partner-carousel owl-carousel">
                        <!-- single partner -->
                        <div class="single-partner">
                            <img src="{{asset('')}}/img/partner.png" alt="">
                        </div>
                        <!-- End of single partner -->

                        <!-- single partner -->
                        <div class="single-partner">
                            <img src="{{asset('')}}/img/partner.png" alt="">
                        </div>
                        <!-- End of single partner -->

                        <!-- single partner -->
                        <div class="single-partner">
                            <img src="{{asset('')}}/img/partner.png" alt="">
                        </div>
                        <!-- End of single partner -->

                        <!-- single partner -->
                        <div class="single-partner">
                            <img src="{{asset('')}}/img/partner.png" alt="">
                        </div>
                        <!-- End of single partner -->
                    </div>
                </div>
                <!--End of  partner carosel inner -->
            </div>
        </div>
    </div>
</section>
<!-- End of our partner -->